server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
    static-path-pattern: /static/**
    converters:
      preferred-json: gson
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
app:
  config:
    omdb:
      api-scheme: http
      api-host: www.omdbapi.com
      api-key: c5ef16e2