server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
thymeleaf:
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  cache: false
app:
  config:
    apikey: c5ef16e2
    api:
      display: http://www.omdbapi.com/?s=Home&apikey={apikey}
      detail: http://www.omdbapi.com/?i={index}&apikey={apikey}